server:
  port: 8080
  servlet:
    context-path: /fulfilment

apiurl: 
  sampleValue: http://localhost:8080/otherservice

  
jwt:
  key: jwt_key
  subject: jwt_subject
  salt: luvookSecret
  expiration: 10

---

#env:
#  port: "$(HTTP_PORT)"

  
server:
  port: 8081
  tomcat: 
    accesslog: 
      pattern: '%{yyyy-MM-dd HH:mm:ss}t\t%s\t%r\t%{User-Agent}i\t%{Referer}i\t%a\t%b'
      enabled: true
    #basedir: C:/Users/pjj/Desktop/jar
  
spring:
  profiles: default

#  data:
#    rest:
#      base-path: api
  
  datasource:
    url: jdbc:mysql://${DATASORUCE_ADDRESS:34.84.76.152:3306}/${DATASORUCE_TABLESPACE:lguplus}
    username: ${DATASORUCE_USERNAME:lguplus}
    password: ${DATASORUCE_PASSWORD:1234}
    driverClassName: com.mysql.cj.jdbc.Driver
      
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
            
  mybatis:
    #mapper-locations: "classpath*:**/mapper.xml"
    configuration-properties:
      aggressiveLazyLoading: false
      lazyLoadingEnabled: true
      lazyLoadTriggerMethods: ""
      mapUnderscoreToCamelCase: true
    
logging:
  level:
    org:
      hibernate:
        type: trace  
      #springframework:
      #  boot: DEBUG

apiurl: 
  sampleValue: http://localhost:8080/otherservice
    
---
spring:
  profiles: docker
  sleuth:
    sampler:
      probability: 1
    web:
      skipPattern: (^cleanup.*|.+favicon.*)

  datasource:
    url: jdbc:mysql://${DATASORUCE_ADDRESS:34.84.76.152:3306}/${DATASORUCE_TABLESPACE:lguplus}
    username: ${DATASORUCE_USERNAME:lguplus}
    password: ${DATASORUCE_PASSWORD:1234}
    driverClassName: com.mysql.cj.jdbc.Driver
      
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
            
  mybatis:
    configuration-properties:
      aggressiveLazyLoading: false
      lazyLoadingEnabled: true
      lazyLoadTriggerMethods: ""
      mapUnderscoreToCamelCase: true
      
---
spring:
  profiles: test
  
  datasource:
    url: jdbc:mysql://34.84.76.152:3306/lguplus
    username: lguplus
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect

  mybatis:
    configuration-properties:
      aggressiveLazyLoading: false
      lazyLoadingEnabled: true
      lazyLoadTriggerMethods: ""
      mapUnderscoreToCamelCase: true        